feed/genbank/.gitignore, feed/genbank/accessionFromGenbank.py, feed/genbank/makeaccessionid2taxonid.py, feed/silva/process_silva.py
This is an initial commit.  This seems to work - creates a accession/taxon/strain tsv file.  File can be reviewed at ot10:/disk2/opentree/genbank.  Hardcoded file counts at lines 96-104 need attention as they change as genbank grows.
=> Add genbank

feed/ncbi/augment_ncbi_taxonomy.py
Initial commit of tool to add strains as terminal taxa to NCBI taxonomy.
=> Augment ncbi

feed/gbif/process_gbif_taxonomy.py, feed/silva/process_silva.py, org/opentreeoflife/smasher/Taxonomy.java
=> Speed up gbif preprocessing

Makefile
Otherwise there's a somewhat mysterious failure message.
=> Ensure that first build has expected ncbi/in

org/opentreeoflife/smasher/Newick.java, org/opentreeoflife/smasher/Taxon.java, org/opentreeoflife/smasher/Taxonomy.java
and a few other Newick improvements.
Moved all Newick processing into a separate class.
It's now possible to load the synthetic tree into smasher (should one want to).
=> Added ability to read quoted Newick tip labels

Makefile, doc/ott2.9.md, feed/fung/fix-if.py, org/opentreeoflife/smasher/Taxonomy.java, taxonomies.py
The main change is getting the correct version of index fungorum; this doesn't show up in the commit log.
=> OTT 2.9 draft 10

org/opentreeoflife/conflict/Articulation.java, org/opentreeoflife/conflict/ConflictAnalysis.java, org/opentreeoflife/server/Services.java, org/opentreeoflife/taxa/Nexson.java, service/README.md, service/service.config.example
This is running on devtree.  To see the fix, compare the following two views:
(wrong) https://tree.opentreeoflife.org/curator/study/view/pg_2847/?tab=trees&tree=tree6609&conflict=ott
(right) https://devtree.opentreeoflife.org/curator/study/view/pg_2847/?tab=trees&tree=tree6609&conflict=ott
For example, the edge to the sister group of Seculamonas ecuadoriensis is resolved in the first (wrong), conflict in the second (right - I believe, haven't actually checked what the taxonomy says).
This PR addresses https://github.com/OpenTreeOfLife/opentree/issues/935 . It also fixes #190.
=> Fix for issue 935 in opentree repo - conflict bug

Makefile, assemble_ott.py, feed/silva/process_silva.py
I'm going to merge this, because (a) I haven't received any comments, (b) it doesn't make things any worse than they are, (c) if it stays on a branch it can be lost or forgotten, (d) any new work on the Makefile should account for these changes.
=> Attempt to reproduce OTT 2.9 from fresh repository

util/find_outliers.py
Reads taxonomy and phylesystem
(1) finds taxa in ingroup that are not under the focal clade according to taxonomy
(2) finds MRCA in taxonomy of tree
Initial commit; needs some more work e.g. around suppressed taxa.
=> rudimentary outliers-finding script

Makefile, doc/ott2.10.md, feed/irmng/process_irmng.py, org/opentreeoflife/server/Services.java, org/opentreeoflife/taxa/Flag.java, org/opentreeoflife/taxa/InterimFormat.java, org/opentreeoflife/taxa/Newick.java, org/opentreeoflife/taxa/Taxonomy.java, resources/captures.json
=> Misc fixes

doc/method/discussion.md, doc/method/introduction.md, doc/method/method-details.md, doc/method/method-intro.md, doc/method/method-sources.md, doc/method/results.md
@jar398 : I've done through and deleted / addressed many of the comments we discussed in our read-through yesterday. If you search for `[JAR:` you will find the ones that still need your attention.
=> Cleaning up comments

doc/method/discussion.md, doc/method/method-details.md, doc/method/method-intro.md, doc/method/results.md
Explain diacritic removal; follow up on my comments on #286; and other miscellaneous edits
=> Misc changes to text

doc/method/data-package/Makefile, doc/method/data-package/README
Initial checkin, I'm expecting requests for changes during review
=> README and Makefile for data package

doc/method/results.md
This section would be much improved by actually performing the measurements suggested, but I'm putting that off in the interest of expediency.  It would probably take at least 4 hours.
Addresses issue #297
=> Rewrite backbone quality section (#297)

Makefile, doc/method/conclusions.md, doc/method/discussion.md, doc/method/make_table_markdown.py, doc/method/to_cite.bib, org/opentreeoflife/smasher/MergeMachine.java, org/opentreeoflife/smasher/UnionTaxonomy.java, org/opentreeoflife/taxa/Taxon.java
Future work section; acknowledgments; update IRMNG reference.
Also counted number of graft events, but now I can't figure out why I did.
=> Punch list for method writeup

assemble_ott.py
See #330 
Does not address the larger question in that issue about prioritizing all of worms over NCBI.
=> use WoRMS for Mollusca

Makefile, bin/christen, curation/adjustments.py, org/opentreeoflife/smasher/AlignmentByName.java, org/opentreeoflife/taxa/InterimFormat.java, org/opentreeoflife/taxa/Taxon.java, org/opentreeoflife/taxa/Taxonomy.java
I think the commit list is as good a summary of the changes as any.
=> A clutch of miscellaneous small improvements

Makefile
thanks @josephwb for spotting this
=> fix copy/paste glitch ('gbif' for 'irmng')

doc/maintenance/new-source.md
=> fix link to file

curation/adjustments.py, curation/amendments.py, ncbi_ott_assignments.py
To be done: create inclusion tests for these. (that would be the germinator repo.)
=> Some OTT patches that somehow didn't make it into OTT 3.0

.gitignore, Makefile, assemble_ott.py, bin/fetch-archive, bin/use-version, doc/maintenance/new-release.md
I wanted to make sure somebody else would have a fighting chance to built OTT, so I tried building it from a fresh repository clone.  There were a couple of minor issues having to do with taxon additions which I believe are fixed by this commit.
It might be nice if the errors in the build were fixed, but they are not serious and they can wait.
=> Make sure that OTT builds in fresh clone

Makefile, import_scripts/eol/README.md, import_scripts/eol/process_eol.py, util/load_eol_page_ids.py
This is a start on addressing #114, but is not finished, as explained in the README that's part of this PR.
I didn't want this work to be stranded on a branch, since it would probably be lost there. I'm requesting that it be added to the master branch even though as currently configured it has no effect on the OTT build.
(attention @hyanwong)
=> EOL page ids

Makefile, bin/store-archive, curation/adjustments.py, curation/amendments.py, doc/maintenance/feedback.md, org/opentreeoflife/taxa/Addition.java, org/opentreeoflife/taxa/Rank.java, org/opentreeoflife/taxa/TsvEdits.java
Wait to merge until we are happy with the draft of ott3.1.
=> Changes for ott3.1

org/opentreeoflife/smasher/AlignmentByName.java, org/opentreeoflife/taxa/InterimFormat.java, org/opentreeoflife/taxa/Synonym.java
This is simple and seems plausible to me, and it compiles, but I haven't tested it yet.
=> Common names - untested
